### ISSUE TITLE
"Haude" method error in calculate_all  

### ISSUE THREAD

**Issue by Darren-Ray** [pyet-org/pyet#54]
Hi, 
When running calculate_all I am getting the error:

 Edf=pyet.calculate_all(tmean=edf["tmean"],wind=edf["Speed"],rs=edf["Radiation"],elevation=ELEV,lat=RLAT,tmax=edf["MaxT"],tmin=edf["MinT"],rhmax=edf["maxRH"],rhmin=edf["MinRH"])

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pyet\combination.py:867 in calculate_all
    pe_df["Haude"] = haude(tmax, rh)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pyet\temperature.py:140 in haude
    ea = check_rh(rh) * e0 / 100

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\ops\common.py:72 in new_method
    return method(self, other)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\arraylike.py:122 in __rmul__
    return self._arith_method(other, roperator.rmul)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\series.py:6259 in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\base.py:1325 in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\ops\array_ops.py:226 in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\ops\array_ops.py:165 in _na_arithmetic_op
    result = func(left, right)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\computation\expressions.py:241 in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\computation\expressions.py:70 in _evaluate_standard
    return op(a, b)

  File ~\AppData\Local\miniconda3\envs\geocube\lib\site-packages\pandas\core\roperator.py:19 in rmul
    return right * left

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

 I am running this in miniconda with pandas 1.5.3 and python 3.10  

It works running the pm_fao56()

**Comment by raoulcollenteur** [comment]
Hi @Darren-Ray,

Sorry for the late response, I hope you still found Pyet useful for your work. Did you try running the example notebook 01_example_zamg.ipynb? I can't replicate the error you got...

Best,
Raoul
