### ISSUE TITLE
Specific humidity to relative humidity 

### ISSUE THREAD

**Issue by PraewKPT** [pyet-org/pyet#68]
Does pyet package support data of specific humidity (xarray)? 
If I didn't have relative humidity (I have specific humidity), how should I do?

**Comment by mvremec** [comment]
Dear PraewKPT, 
Sorry for my late response. PyEt does not directly support data of specific humidity, however, you can use the specific humidity to compute the actual vapor pressure. Another option is to use PyEt methods that do not require the relative humidity,

The formula to convert specific humidity (`q`) to actual vapor pressure (`e`) is given by:
ea = (q * P) / (ε + q * (1 - ε))
where:
- `ea` is the actual vapor pressure,
- `q` is the specific humidity (dimensionless or in kg/kg),
- `P` is the total air pressure (often assumed to be at sea level if not given, which is approximately 1013.25 hPa or mb),
- `ε` is the ratio of the molar mass of water vapor to the molar mass of dry air, approximately equal to 0.622.
 
Cheers, Matevz
